<?php

namespace BlogBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestPosts($limit = null)
    {
        $select = $this->createQueryBuilder('post')
            ->select('post')
            ->addOrderBy('post.created', 'DESC');

        if (false === is_null($limit))
            $select->setMaxResults($limit);

        return $select->getQuery()
            ->getResult();
    }

    // Doctrine\ORM\EntityRepository
    public function createQueryBuilder($alias, $indexBy = NULL)
    {
        return $this->_em->createQueryBuilder()
            ->select($alias)
            ->from($this->_entityName, $alias);
    }
}
