blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Blog:index }

blog_about:
    path:     /about
    defaults: { _controller: BlogBundle:Blog:about }

blog_show:
    path:     /{id}
    defaults: { _controller: BlogBundle:Post:show }
